### ISSUE TITLE
How to remove the mask when characters are deleted from the entry text ?

### ISSUE THREAD

**Issue by vimalsaifudin** [TBertuzzi/Xamarin.Forms.MaskedEntry#1]
How to remove the mask when characters are deleted from the entry text ?

**Comment by NhanNTT249** [comment]
Same question. Please help us

**Comment by NhanNTT249** [comment]
@vimalsaifudin vi
You can using code: 

  `private void OnEntryTextChanged(object sender, TextChangedEventArgs args)
        {
            var entry = sender as Entry;
            var text = entry.Text;

            if (string.IsNullOrWhiteSpace(text) || _positions == null) return;

            if (text.Length > Mask.Length)
            {
                entry.Text = text.Remove(text.Length - 1);
                return;
            }

            string newText = Regex.Replace(text, "[^.0-9]", "");
            foreach (var position in _positions)
            {
                if (newText.Length >= position.Key + 1)
                {
                    var value = position.Value.ToString();
                    var textSub = newText.Substring(position.Key, 1);

                    if (textSub != value) newText = newText.Insert(position.Key, value);
                }
            }

            if (entry.Text != newText) entry.Text = newText;
        }`

**Comment by MohanaSundharamMurugan** [comment]
what you mean by _positions?
